dados <- read.csv("C:\\comerciais.csv", header=TRUE)
summary(dados)
attach(dados)
table(teste)
table(duracao)
plot(duracao, teste)
cor(duracao, teste)
lm(formula = teste~duracao)
abline(lm(teste~duracao))
r = lm(teste~duracao); summary(r)
confint(r, level=.95)
predict(r, data.frame(duracao=10), interval="confidence", level = 0.95)
predict(r, data.frame(duracao=100), interval="confidence", level = 0.95)
predict(r, data.frame(duracao=40), interval="confidence", level = 0.95)
predict(r, data.frame(duracao=40), interval="prediction", level = 0.95)
